"""
Catalogue descriptif des maladies — base de connaissances pour la détection.

Chaque entrée contient des caractéristiques visuelles structurées utilisées
par disease_detector.py pour la comparaison multi-critères.

Cultures : tomate, maïs, manioc, riz, pomme de terre.
"""


def _base(
	name, scientific, symptoms, causes, treatment, prevention, severity, plant,
	type_taches, couleur_taches, taille_taches, disposition_taches,
	texture_feuille, couleur_generale, zones_atteintes, progression_maladie,
):
	"""Construit un enregistrement complet (champs descriptifs + texte libre)."""
	return {
		"disease_name": name,
		"scientific_name": scientific,
		"symptoms": symptoms,
		"causes": causes,
		"treatment": treatment,
		"prevention": prevention,
		"severity": severity,
		"plant_type": plant,
		"type_taches": type_taches,
		"couleur_taches": couleur_taches,
		"taille_taches": taille_taches,
		"disposition_taches": disposition_taches,
		"texture_feuille": texture_feuille,
		"couleur_generale": couleur_generale,
		"zones_atteintes": zones_atteintes,
		"progression_maladie": progression_maladie,
		"leaf_color": couleur_generale,
		"leaf_texture": texture_feuille,
	}


def get_descriptive_catalog():
	"""Retourne la liste complète des maladies avec profils visuels structurés."""
	catalog = []

	# =========================================================================
	# TOMATE (6 maladies)
	# =========================================================================
	catalog.extend([
		_base(
			"Mildiou", "Phytophthora infestans",
			"Taches brunes huileuses, duvet blanc au revers, pourriture rapide.",
			"Oomycète favorisé par humidité et fraîcheur.",
			"Fongicide systémique, retirer feuilles atteintes.",
			"Rotation, semences saines, aération.",
			"élevé", "tomate",
			"taches irrégulières fusionnées",
			"brun foncé, vert jaunissant",
			"moyenne à grande",
			"dispersée, progresse du bas vers le haut",
			"huileuse, humidifiée",
			"vert jaunissant puis brun",
			"bord des feuilles, feuilles basses",
			"rapide",
		),
		_base(
			"Alternariose", "Alternaria solani",
			"Taches brunes concentriques en cible, nécrose sèche.",
			"Champignon sur plantes affaiblies.",
			"Fongicides, nettoyage des débris.",
			"Rotation, élimination résidus.",
			"modéré", "tomate",
			"taches rondes concentriques",
			"brun foncé, centre plus clair",
			"petite à moyenne",
			"éparses, regroupées par zones",
			"nécrotique, sèche",
			"vert avec taches brunes",
			"limbe foliaire, feuilles moyennes",
			"modérée",
		),
		_base(
			"Tache bactérienne", "Xanthomonas euvesicatoria",
			"Taches angulaires brunes, aspect huileux, chute foliaire.",
			"Bactérie par eau et outils.",
			"Cuivre préventif, retirer feuilles infectées.",
			"Désinfection outils, éviter arrosage foliaire.",
			"modéré", "tomate",
			"taches angulaires localisées",
			"brun foncé, halo jaune",
			"petite à moyenne",
			"entre nervures, bords, regroupées",
			"luisante, légèrement humide",
			"vert avec taches brunes",
			"limbe, nervures secondaires",
			"modérée à rapide",
		),
		_base(
			"Cercosporiose", "Cercospora spp.",
			"Petites taches rondes brun foncé, centre gris ou jaune pâle.",
			"Champignon en conditions humides.",
			"Fongicides, retirer feuilles touchées.",
			"Espacement, éviter aspersion.",
			"faible", "tomate",
			"taches rondes localisées",
			"brun foncé, centre jaune pâle",
			"petite",
			"éparses, parfois sur les bords",
			"légèrement rugueuse",
			"vert avec petites taches",
			"surface foliaire, bords",
			"lente à modérée",
		),
		_base(
			"Mosaïque virale", "Tobamovirus / Potyvirus",
			"Motifs jaune-vert en mosaïque, déformation, croissance réduite.",
			"Virus par insectes ou contact.",
			"Aucun curatif, détruire plants infectés.",
			"Semences saines, lutte vecteurs.",
			"élevé", "tomate",
			"mosaïque diffuse sans taches nettes",
			"jaune pâle et vert clair mélangés",
			"aucune tache individuelle",
			"uniforme sur toute la feuille",
			"rugueuse, déformée",
			"mosaïque jaune et vert",
			"feuille entière, jeunes pousses",
			"progressive",
		),
		_base(
			"Oïdium", "Oidium neolycopersici",
			"Poudre blanche sur face supérieure, feuilles recroquevillées.",
			"Champignon temps sec, faible aération.",
			"Soufre ou fongicide, retirer feuilles.",
			"Aération, éviter excès azote.",
			"modéré", "tomate",
			"poudre blanche sans taches distinctes",
			"blanc poudreux sur vert",
			"couvre la surface",
			"uniforme, couvre la feuille",
			"poudreuse, farineuse",
			"vert recouvert de blanc",
			"surface supérieure des feuilles",
			"modérée",
		),
		_base(
			"Chlorose nutritive", "Carence en fer / magnésium",
			"Jaunissement uniforme entre nervures, peu de nécrose.",
			"Carence minérale, sol calcaire ou pH élevé.",
			"Correction fertilisation, chélate de fer.",
			"Analyse sol, fertilisation équilibrée.",
			"faible", "tomate",
			"pas de taches, jaunissement uniforme",
			"jaune pâle",
			"aucune",
			"uniforme, entre nervures",
			"lisse",
			"jaune pâle, vert pâle",
			"feuille entière, jeunes feuilles d'abord",
			"lente",
		),
		_base(
			"Fusariose", "Fusarium oxysporum",
			"Flétrissement unilatéral, jaunissement bas, nécrose vasculaire.",
			"Champignon du sol dans vaisseaux.",
			"Éliminer plants, pas de curatif fiable.",
			"Variétés résistantes, rotation.",
			"élevé", "tomate",
			"pas de taches foliaires nettes",
			"jaune puis brun",
			"aucune",
			"feuilles basses d'abord, un côté",
			"flétrie, sèche",
			"jaune puis brun, vert résiduel",
			"feuilles basses, demi-plante",
			"rapide",
		),
	])

	# =========================================================================
	# MAÏS (5 maladies)
	# =========================================================================
	catalog.extend([
		_base(
			"Rouille du maïs", "Puccinia sorghi",
			"Pustules orangées à brunes, souvent en lignes, chute précoce.",
			"Champignon vent + humidité.",
			"Fongicides de contact.",
			"Variétés résistantes, rotation.",
			"modéré", "maïs",
			"pustules nombreuses",
			"orange, brun clair",
			"très petite",
			"alignées, bord des feuilles, revers",
			"poudreuse",
			"vert avec pustules orangées",
			"limbe, souvent revers foliaire",
			"modérée à rapide",
		),
		_base(
			"Helminthosporiose du maïs", "Exserohilum turcicum",
			"Taches allongées brun foncé en fuseau, peut couvrir la feuille.",
			"Champignon résidus + humidité.",
			"Fongicides, destruction résidus.",
			"Rotation, variétés tolérantes.",
			"élevé", "maïs",
			"taches allongées fusionnées",
			"brun foncé, gris au centre",
			"moyenne à grande",
			"le long des nervures, fuseau",
			"nécrotique sèche",
			"vert puis brun",
			"feuilles médianes et hautes",
			"rapide en conditions humides",
		),
		_base(
			"Charbon du maïs", "Ustilago maydis",
			"Galles blanches puis noires sur épis, tiges, parfois feuilles.",
			"Champignon chaleur + humidité.",
			"Brûler plants infectés.",
			"Rotation, semences traitées.",
			"modéré", "maïs",
			"excroissances/galles",
			"blanc puis noir",
			"grande",
			"localisée sur organes",
			"galle molle puis poudre noire",
			"vert avec bosses",
			"épis, tiges, rarement feuilles",
			"modérée",
		),
		_base(
			"Anthracnose du maïs", "Colletotrichum graminicola",
			"Taches sombres sur feuilles, lésions sur tiges et épis.",
			"Champignon résidus infectés.",
			"Fongicides, destruction résidus.",
			"Rotation, semences propres.",
			"modéré", "maïs",
			"taches irrégulières",
			"brun foncé, noir",
			"moyenne",
			"éparses, regroupées",
			"spongieuse puis sèche",
			"vert taché de brun",
			"feuilles et tiges",
			"modérée",
		),
		_base(
			"Stries du maïs (virus MDMV)", "Maize dwarf mosaic virus",
			"Rayures jaune-vert, raccourcissement, mosaïque sur jeunes feuilles.",
			"Virus par pucerons.",
			"Détruire plants infectés.",
			"Semences saines, lutte pucerons.",
			"élevé", "maïs",
			"mosaïque et rayures",
			"jaune pâle, vert clair",
			"aucune tache ronde",
			"uniforme, le long des nervures",
			"rugueuse",
			"jaune et vert marbré",
			"feuilles jeunes, cœur",
			"progressive",
		),
		_base(
			"Pourriture des racines du maïs", "Fusarium verticillioides",
			"Flétrissement, jaunissement général, racines molles.",
			"Champignon du sol humide.",
			"Gestion résidus, pas de curatif.",
			"Drainage, rotation.",
			"élevé", "maïs",
			"pas de taches nettes sur feuilles",
			"jaune pâle",
			"aucune",
			"uniforme, feuilles basses",
			"flétrie",
			"jaunissement général",
			"plante entière, racines",
			"rapide",
		),
	])

	# =========================================================================
	# MANIOC (5 maladies)
	# =========================================================================
	catalog.extend([
		_base(
			"Mosaïque du manioc", "Cassava mosaic virus",
			"Mosaïque jaune-vert, déformation des lobes, croissance réduite.",
			"Virus par pucerons et boutures.",
			"Détruire plants infectés.",
			"Boutures saines, lutte vecteurs.",
			"élevé", "manioc",
			"mosaïque diffuse",
			"jaune pâle et vert clair",
			"aucune tache ronde",
			"uniforme sur lobes",
			"rugueuse, déformée",
			"mosaïque jaune et vert",
			"feuilles entières, jeunes pousses",
			"progressive",
		),
		_base(
			"Anthracnose du manioc", "Colletotrichum gloeosporioides",
			"Taches brunes sur feuilles, chancres tiges et racines.",
			"Champignon humidité + blessures.",
			"Fongicides, retirer tissus.",
			"Boutures saines, drainage.",
			"modéré", "manioc",
			"taches rondes localisées",
			"brun foncé",
			"petite à moyenne",
			"éparses, bords des lobes",
			"nécrotique friable",
			"vert avec taches brunes",
			"limbe foliaire, tiges",
			"modérée",
		),
		_base(
			"Tache brune du manioc", "Corynespora cassiicola",
			"Taches brunes bord net, centre plus clair, chute foliaire.",
			"Champignon humidité prolongée.",
			"Fongicides, éliminer débris.",
			"Éclaircissage, rotation.",
			"faible", "manioc",
			"taches rondes localisées",
			"brun foncé, centre clair",
			"petite",
			"éparses, bords des feuilles",
			"sèche, feutrée",
			"vert avec petites taches",
			"surface foliaire",
			"lente à modérée",
		),
		_base(
			"Flétrissement bactérien du manioc", "Xanthomonas axonopodis",
			"Flétrissement, branches mortes, écorce qui se détache.",
			"Bactérie pluie et outils.",
			"Retirer plants, pas de curatif.",
			"Désinfection, boutures saines.",
			"élevé", "manioc",
			"pas de taches rondes",
			"jaune puis brun",
			"aucune",
			"feuilles entières, tiges",
			"flétrie, épaissie",
			"jaune puis brun",
			"tiges, feuilles, plante entière",
			"rapide",
		),
		_base(
			"Bactériose foliaire du manioc", "Xanthomonas axonopodis pv. manihotis",
			"Taches angulaires entre nervures, aspect huileux.",
			"Bactérie par pluie.",
			"Retirer feuilles très atteintes.",
			"Outils propres, espacement.",
			"modéré", "manioc",
			"taches angulaires",
			"brun, halo jaune",
			"petite à moyenne",
			"entre nervures",
			"luisante",
			"vert taché",
			"limbe foliaire",
			"modérée",
		),
	])

	# =========================================================================
	# RIZ (5 maladies)
	# =========================================================================
	catalog.extend([
		_base(
			"Pyriculariose", "Pyricularia oryzae",
			"Taches en forme de losange, centre gris, bord brun, brûlure du collier.",
			"Champignon humidité et rosée.",
			"Fongicides spécifiques.",
			"Rotation, semences saines.",
			"élevé", "riz",
			"taches en losange",
			"brun foncé, centre gris",
			"moyenne",
			"éparses, le long des nervures",
			"nécrotique craquelée",
			"vert avec taches brunes",
			"feuilles, collier de la tige",
			"rapide",
		),
		_base(
			"Tache brune du riz", "Bipolaris oryzae",
			"Taches circulaires brunes, centre clair, perte foliaire.",
			"Champignon pluies fréquentes.",
			"Fongicides, réduire humidité foliaire.",
			"Rotation, variétés résistantes.",
			"modéré", "riz",
			"taches rondes localisées",
			"brun foncé, centre clair",
			"petite à moyenne",
			"éparses sur le limbe",
			"sèche, en anneau",
			"vert taché de brun",
			"feuilles, parfois gaines",
			"modérée",
		),
		_base(
			"Bakanae", "Fusarium fujikuroi",
			"Plantules trop hautes, jaunissement, dessèchement.",
			"Champignon semences contaminées.",
			"Traitement semences, éliminer plants.",
			"Graines certifiées.",
			"élevé", "riz",
			"pas de taches typiques",
			"jaune pâle",
			"aucune",
			"uniforme, plantules",
			"molle, fine",
			"jaune pâle",
			"jeunes plants, coléoptile",
			"rapide",
		),
		_base(
			"Brûlure des gaines", "Rhizoctonia solani",
			"Lésions ovales gris-brun sur gaines, plants couchés.",
			"Champignon sol humide.",
			"Fongicides, drainage.",
			"Eau maîtrisée, densité réduite.",
			"modéré", "riz",
			"taches ovales sur gaines",
			"gris-brun",
			"moyenne",
			"à la base des tiges",
			"molle puis sèche",
			"vert, gaines brunâtres",
			"gaines, base de tige",
			"modérée à rapide",
		),
		_base(
			"Strie virale du riz", "Rice stripe virus",
			"Rayures chlorotiques, stries jaunes, raccourcissement.",
			"Virus par cicadelles.",
			"Détruire foyers.",
			"Variétés tolérantes, lutte insectes.",
			"élevé", "riz",
			"rayures et mosaïque",
			"jaune pâle, vert clair",
			"aucune tache ronde",
			"le long des nervures",
			"rugueuse",
			"jaune et vert strié",
			"feuilles jeunes",
			"progressive",
		),
	])

	# =========================================================================
	# POMME DE TERRE (5 maladies)
	# =========================================================================
	catalog.extend([
		_base(
			"Mildiou de la pomme de terre", "Phytophthora infestans",
			"Taches brunes huileuses, duvet blanc, pourriture tubercules.",
			"Oomycète humidité + fraîcheur.",
			"Fongicide, retirer parties atteintes.",
			"Rotation, semences certifiées.",
			"élevé", "pomme de terre",
			"taches irrégulières fusionnées",
			"brun foncé, vert jaunissant",
			"moyenne à grande",
			"dispersée, feuilles basses d'abord",
			"huileuse",
			"vert jaunissant puis brun",
			"feuilles, tiges, tubercules",
			"rapide",
		),
		_base(
			"Rhizoctone noir", "Rhizoctonia solani",
			"Taches brunes sur tubercules, pourriture sèche racines.",
			"Champignon sol et débris.",
			"Fongicides sol, éliminer tubercules atteints.",
			"Rotation, sol drainé.",
			"modéré", "pomme de terre",
			"taches sur tubercules",
			"brun sombre, noir",
			"moyenne",
			"localisée sur tubercules",
			"dure, sèche",
			"vert, tubercules tachés",
			"tubercules, racines, collet",
			"modérée",
		),
		_base(
			"Gale argentée", "Alternaria alternata",
			"Taches brunes en cible sur feuilles, aspect argenté sur tubercules.",
			"Champignon résidus.",
			"Fongicides, stockage sec.",
			"Rotation, ventilation.",
			"modéré", "pomme de terre",
			"taches rondes concentriques",
			"brun avec centre clair",
			"petite à moyenne",
			"éparses sur feuilles",
			"sèche, légèrement rugueuse",
			"vert taché",
			"feuilles, tubercules en stockage",
			"modérée",
		),
		_base(
			"Alternariose des tubercules", "Alternaria solani",
			"Taches brunes sèches sur tubercules et feuilles.",
			"Champignon stockage humide.",
			"Tri des tubercules, fongicide.",
			"Stockage frais et sec.",
			"modéré", "pomme de terre",
			"taches rondes localisées",
			"brun foncé",
			"petite à moyenne",
			"éparses",
			"sèche, nécrotique",
			"brun sur vert ou tubercule",
			"feuilles et tubercules",
			"lente à modérée",
		),
		_base(
			"Virus Y de la pomme de terre", "Potato virus Y",
			"Mosaïque, jaunissement, déformation feuilles.",
			"Virus par pucerons.",
			"Détruire plants, pas de curatif.",
			"Semences certifiées, lutte pucerons.",
			"élevé", "pomme de terre",
			"mosaïque diffuse",
			"jaune pâle, vert clair",
			"aucune tache ronde",
			"uniforme",
			"rugueuse, déformée",
			"mosaïque jaune et vert",
			"feuilles, croissance réduite",
			"progressive",
		),
		_base(
			"Chlorose de la pomme de terre", "Carence nutritionnelle",
			"Jaunissement léger à modéré, peu de taches.",
			"Carence azote ou fer.",
			"Fertilisation adaptée.",
			"Analyse sol.",
			"faible", "pomme de terre",
			"pas de taches",
			"jaune pâle",
			"aucune",
			"uniforme",
			"lisse",
			"jaune pâle",
			"feuilles, surtout apex",
			"lente",
		),
	])

	# =========================================================================
	# ARACHIDE (4 maladies)
	# =========================================================================
	catalog.extend([
		_base(
			"Cercosporiose précoce de l'arachide", "Cercospora arachidicola",
			"Petites taches brunes cernées de jaune sur les feuilles, bord des nervures.",
			"Champignon favorisé par humidité et chaleur.",
			"Fongicides à base de cuivre, retirer feuilles atteintes.",
			"Aération, espacement, éviter l'humidité stagnante.",
			"modéré", "arachide",
			"taches rondes localisées",
			"brun clair avec halo jaune",
			"petite",
			"éparses, le long des nervures",
			"légèrement rugueuse",
			"vert taché de brun",
			"feuilles, nervures",
			"modérée",
		),
		_base(
			"Cercosporiose tardive de l'arachide", "Cercospora personata",
			"Taches plus larges, centre gris clair et bord brun foncé sur les feuilles.",
			"Champignon prospérant sur feuilles humides et débris verts.",
			"Fongicides, éliminer les feuilles gravement touchées.",
			"Ramassage des débris, rotation, intercaler des cultures non hôtes.",
			"élevé", "arachide",
			"taches irrégulières",
			"brun foncé, centre gris",
			"moyenne",
			"dispersée, parfois agrégée",
			"nécrotique sterile",
			"vert avec larges taches brunes",
			"surface foliaire",
			"modérée à rapide",
		),
		_base(
			"Rouille de l'arachide", "Puccinia arachidis",
			"Petites pustules orange sur la face inférieure des feuilles, dessèchement.",
			"Champignon parasitaire transmis par le vent et l'humidité.",
			"Fongicides de contact, enlever les feuilles infectées.",
			"Espacement, éviter le sur-arrosage, variétés résistantes.",
			"modéré", "arachide",
			"pustules nombreuses",
			"orange à brun clair",
			"très petite",
			"répartie sur les feuilles, surtout le revers",
			"poudreuse",
			"vert avec pustules orangées",
			"feuilles inférieures",
			"modérée",
		),
		_base(
			"Rosette de l'arachide", "Arachis hypogaea virus (AHSV)",
			"Jaunissement et rubanement des feuilles, déformation et attaque en mosaïque.",
			"Virus vecteur par pucerons et acariens.",
			"Détruire plants infectés, utiliser semences certifiées.",
			"Lutte des vecteurs, désherbage, semences saines.",
			"élevé", "arachide",
			"mosaïque diffuse",
			"jaune pâle et vert clair",
			"aucune tache ronde",
			"uniforme",
			"rugueuse",
			"jaune et vert marbré",
			"feuilles entières",
			"progressive",
		),
	])

	# =========================================================================
	# MIL (3 maladies)
	# =========================================================================
	catalog.extend([
		_base(
			"Mildiou du mil", "Peronosclerospora sorghi",
			"Taches huileuses jaunes sur les feuilles, duvet blanc à l'arrière.",
			"Oomycète favorisé par humidité et rosée matinale.",
			"Fongicides, élimination des plantes atteintes.",
			"Rotation, éviter l'irrigation foliaire, semences saines.",
			"élevé", "mil",
			"taches irrégulières fusionnées",
			"jaune huileux",
			"moyenne",
			"dispersée, entre nervures",
			"huileuse",
			"vert jaunissant",
			"feuilles, base des tiges",
			"rapide",
		),
		_base(
			"Rouille du mil", "Puccinia sorghi",
			"Pustules orange-brunes alignées, feuilles sèches et cassantes.",
			"Champignon propagé par le vent dans les conditions chaudes.",
			"Fongicides, retirer feuilles infectées.",
			"Cultures résistantes, espacement, aération.",
			"modéré", "mil",
			"pustules nombreuses",
			"orange, brun clair",
			"très petite",
			"en lignes, le long des nervures",
			"poudreuse",
			"vert avec pustules orangées",
			"feuilles moyenne à supérieure",
			"modérée",
		),
		_base(
			"Helminthosporiose du mil", "Exserohilum turcicum",
			"Taches allongées brunes, parfois cerclées, sur les feuilles.",
			"Champignon résiduel aggravé par l'humidité.",
			"Fongicides, enlever résidus infectés.",
			"Rotation, semences propres, réduction de l'humidité.",
			"modéré", "mil",
			"taches allongées",
			"brun foncé",
			"moyenne à grande",
			"alignées, le long des nervures",
			"nécrotique",
			"vert taché de brun",
			"feuilles et nervures",
			"modérée à rapide",
		),
	])

	# =========================================================================
	# SORGHO (3 maladies)
	# =========================================================================
	catalog.extend([
		_base(
			"Anthracnose du sorgho", "Colletotrichum sublineolum",
			"Taches brunes à noires sur les feuilles, parfois en forme d'anneau.",
			"Champignon transmis par résidus et pluie.",
			"Fongicides, enlever feuilles atteintes.",
			"Rotation, semences saines, espacement.",
			"modéré", "sorgho",
			"taches irrégulières",
			"brun foncé, noir",
			"moyenne",
			"dispersée, regroupée par zones",
			"nécrotique",
			"vert taché de brun",
			"feuilles, tiges basses",
			"modérée",
		),
		_base(
			"Rouille du sorgho", "Puccinia purpurea",
			"Pustules rouille sur les feuilles, dessèchement des bords foliaires.",
			"Champignon favorisé par chaleur et humidité.",
			"Fongicides de contact, enlever feuilles infectées.",
			"Variétés résistantes, rotation, aération.",
			"modéré", "sorgho",
			"pustules nombreuses",
			"orange foncé, brun",
			"très petite",
			"le long des nervures, faces des feuilles",
			"poudreuse",
			"vert avec pustules orangées",
			"feuilles supérieures",
			"modérée",
		),
		_base(
			"Mildiou du sorgho", "Peronosclerospora sorghi",
			"Taches jaunâtres huileuses sur les feuilles, duvet gris à l'arrière.",
			"Oomycète propagé par humidité et rosée.",
			"Fongicides, retirer feuilles atteintes.",
			"Semences saines, irrigation contrôlée.",
			"élevé", "sorgho",
			"taches irrégulières fusionnées",
			"jaune huileux",
			"moyenne",
			"dispersée, entre nervures",
			"huileuse",
			"vert jaunissant",
			"feuilles, jeunes pousses",
			"rapide",
		),
	])

	return catalog
